name: CICD
run-name: Release To Play Store
on:
  workflow_dispatch:
  schedule: 
    # Run on the 1st and 15th of every month
    - cron: '0 15 1,15 * *'

jobs:
  cicd:
    runs-on: ubuntu-latest
    name: CICD
    steps:    
      - uses: laguna-studios/fhs@bcd5b8fc3efcbaac9b0b9901d55d2caf316d8524
        with:
          keystore_base64: ${{ secrets.KEYSTORE }}
          key_properties_file: ${{ secrets.KEY_PROPERTIES }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
          package_name: de.seniorlaguna.currency_calculator
