name: Playground
run-name: Playground
on:
  push:
  workflow_dispatch:

jobs:
  cicd:
    runs-on: ubuntu-latest
    name: Playground
    steps:    
      - name: Playground
        run: |
          echo ${{ vars.CONTENT }}
