name: Playground
run-name: Playground
on:
  workflow_dispatch:

jobs:
  cicd:
    runs-on: ubuntu-latest
    name: Playground
    steps:    
      - name: Playground
        run: |
          echo ${{ secrets.KEY_PROPERTIES }} | 
          echo ${{ vars.CONTENT }} | sed s/"storeFile=.*"/storeFile=app.jks/
